language: go       
       
go:        
    - 1.3      
    - tip      
       
before-script:     
    - go get code.google.com/p/go.net/websocket

notifications:
    irc:
        channels:
            - "tardis.nerdlife.de#g0"
        template:
            - "%{repository_name}/%{branch} (#%{build_number}) - Build \x033%{result} \x03in %{duration}."
            - "Commit by %{author}: %{commit_message} %{compare_url}"
