language: go       
       
go:        
    - 1.3      
    - tip      
       
before-script:     
    - go get code.google.com/p/go.net/websocket

notifications:
    irc:
        channels:
            - "tardis.nerdlife.de#g0"
        on_success:
            template:
                - "%{repository_name}/%{branch} (#{build_number}) - Build ^C3%{result}^C1 in %{duration}."
                - "Commit by %{author}: %{commit_message} %{compare_url}"
        on_failure:
            template:
                - "%{repository_name}/%{branch} (#%{build_number} - Build ^C4%{result}^C1 in %{duration}"
                - "Commit by %{author}: %{commit_message} %{compare_url}"
